num_data: 100
record_rules: 
  field01: 
    pattern: 
      - 
        - 
          - "head1_"
          - 70
        - 
          - "head2_"
          - 25
        - 
          - "head3_"
          - 5
    db_column: "postcd"
db_pass: "tdgpass"
sql: "SELECT postcd FROM a;"
proc_null_value: "NULL"
db_user: "tdg"
need_header: true
eol: "\n"
