num_data: 100
record_rules: 
  field01: 
    pattern: 
      - 
        - "head1_"
        - "head2_"
        - "head3_"
    db_column: "postcd"
db_pass: tdgpass
sql: "SELECT postcd FROM a;"
proc_null_value: "NULL"
db_user: tdg
need_header: true
eol: "\n"
