num_data: 100
record_rules: 
  field01: 
    pattern: 
      - 
        - 
          - 
            - "○"
            - 75
          - 
            - "△"
            - 20
          - 
            - "×"
            - 5
        - 10
need_header: true
eol: "\n"
