num_data: 100
record_rules: 
  field01: 
    pattern: 
      - 
        - 
          - 
            - "common"
            - 75
          - 
            - "uncommon"
            - 20
          - 
            - "rare"
            - 5
need_header: true
eol: "\n"
