num_data: 100
record_rules: 
  field01: 
    timestamp: 
      - 
        - "2010-01-01 00:00:00"
        - "2012-12-31 23:59:59"
        - 9
      - 
        - "2013-01-01 00:00:00"
        - "2015-12-31 23:59:59"
        - 1
need_header: true
eol: "\n"
