num_data: 100
record_rules: 
  field01: 
    seq: 1
    pattern: 
      - 
        - "Pattern::UNDER_SCORE"
    master: 
      a: "postcd"
masters: 
  - 
    - "./master/a.csv"
    - "population"
null_value: "NULL"
need_header: true
eol: "\n"
